In [10]:
import numpy as np

In [16]:
v = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
print(v.shape)

(3, 3)


In [21]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = x + y
print(z)

[5 7 9]


In [23]:
print(z+2)

[ 7  9 11]


In [24]:
x = np.linspace(0, 1, 5)
print(x)

[0.   0.25 0.5  0.75 1.  ]


In [25]:
print(x ** 2)

[0.     0.0625 0.25   0.5625 1.    ]


In [27]:
w = np.sin(x)
print(w)

[0.         0.24740396 0.47942554 0.68163876 0.84147098]


In [34]:
x = np.array([4,3,5,2,1])
print(np.max(x))
print(np.sort(x))
w = np.array([3, 4, 1, 2, 2, 4])
print(np.unique(w))

5
[1 2 3 4 5]
[1 2 3 4]


In [36]:
X = np.arange(1,37).reshape(6,6)
print(X)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]


In [42]:
V = np.array([10, 4])
W = np.array([4, 8])
Z = V-W
print(Z)

[ 6 -4]


In [45]:
import pandas as pd
data = pd.DataFrame (
        {'id': [ 1,2,3,4,5,6,7,8] ,
        'Label': ['green','green','green','green',
                  'red','red','red','red'],
        'Height': [5, 5.5, 5.33, 5.75,
                   6.00, 5.92, 5.58, 5.92],
        'Weight': [100, 150, 130, 150 ,
                   180, 190, 170, 165],
         
        'Foot': [6, 8, 7, 9, 13, 11, 12, 10]} ,
         columns = ['id','Height','Weight',
                      'Foot','Label'] )
print(data)

   id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red


In [46]:
data.describe()

id    Height      Weight      Foot
count  8.00000  8.000000    8.000000   8.00000
mean   4.50000  5.625000  154.375000   9.50000
std    2.44949  0.343428   28.962722   2.44949
min    1.00000  5.000000  100.000000   6.00000
25%    2.75000  5.457500  145.000000   7.75000
50%    4.50000  5.665000  157.500000   9.50000
75%    6.25000  5.920000  172.500000  11.25000
max    8.00000  6.000000  190.000000  13.00000

In [51]:
height = np.array([5,5.5,5.33,5.75,6,5.92,5.58,5.92])
weight = np.array([6,8,7,9,13,11,12,10])
correlation = np.corrcoef(height,weight)[0][1] #Pearson correlation
print(correlation)

0.8219319721553828
