In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
mean = np.mean(x)
mean

np.float64(5.5)

In [4]:
np.std(x)

np.float64(2.8722813232690143)

In [8]:
from timeit import timeit
from random import random
n = 1000

x_list = [ random() for i in range(n) ]
y_list = [ random() for i in range(n) ]
timeit()
z_list = [ x_list[i] + y_list[i] for i in range(n) ]

In [9]:
np.arange(0 ,5, 1)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(5, dtype=float)

array([0., 0., 0., 0., 0.])

In [12]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [13]:
np.diag([5, 10])

array([[ 5,  0],
       [ 0, 10]])

In [14]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
z

array([5, 7, 9])

In [15]:
w = 2 + y
w

array([6, 7, 8])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
2 * np.linspace(0, 1, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
np.sin(np.linspace(0, 1, 5))

array([0.        , 0.24740396, 0.47942554, 0.68163876, 0.84147098])

In [21]:
np.arange(1, 37).reshape(6, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [22]:
np.arange(1, 37).reshape(6, 6).transpose()

array([[ 1,  7, 13, 19, 25, 31],
       [ 2,  8, 14, 20, 26, 32],
       [ 3,  9, 15, 21, 27, 33],
       [ 4, 10, 16, 22, 28, 34],
       [ 5, 11, 17, 23, 29, 35],
       [ 6, 12, 18, 24, 30, 36]])

In [23]:
V = np.array([10,4])
W = np.array([4,8])
Z = V - W
Z

array([ 6, -4])

In [24]:
np.linalg.norm(Z)

np.float64(7.211102550927978)

In [26]:
np.linalg.norm(Z, ord=1)

np.float64(10.0)

In [27]:
x = np.array([2, 5, 1, 3])
np.mean(x)

np.float64(2.75)

In [28]:
np.var(x)

np.float64(2.1875)

In [29]:
np.std(x)

np.float64(1.479019945774904)

In [31]:
import pandas as pd
data = pd.DataFrame (
        {'id': [ 1,2,3,4,5,6,7,8] ,
        'Label': ['green','green','green','green',
                  'red','red','red','red'],
        'Height': [5, 5.5, 5.33, 5.75,
                   6.00, 5.92, 5.58, 5.92],
        'Weight': [100, 150, 130, 150 ,
                   180, 190, 170, 165],
        'Foot': [6, 8, 7, 9, 13, 11, 12, 10]} ,
         columns = ['id','Height','Weight',
                      'Foot','Label'] )
                      
print(data)

   id  Height  Weight  Foot  Label
0   1    5.00     100     6  green
1   2    5.50     150     8  green
2   3    5.33     130     7  green
3   4    5.75     150     9  green
4   5    6.00     180    13    red
5   6    5.92     190    11    red
6   7    5.58     170    12    red
7   8    5.92     165    10    red


In [32]:
data.describe()

id    Height      Weight      Foot
count  8.00000  8.000000    8.000000   8.00000
mean   4.50000  5.625000  154.375000   9.50000
std    2.44949  0.343428   28.962722   2.44949
min    1.00000  5.000000  100.000000   6.00000
25%    2.75000  5.457500  145.000000   7.75000
50%    4.50000  5.665000  157.500000   9.50000
75%    6.25000  5.920000  172.500000  11.25000
max    8.00000  6.000000  190.000000  13.00000

In [34]:
height = np.array([5,5.5,5.33,5.75,6,5.92,5.58,5.92])
weight = np.array([6,8,7,9,13,11,12,10])
correlation = np.corrcoef(height, weight) 
correlation

array([[1.        , 0.82193197],
       [0.82193197, 1.        ]])

In [36]:
height = np.array([5,5.5,5.33,5.75])
weight = np.array([6,8,7,9])
correlation = np.corrcoef(height, weight)
correlation

array([[1.        , 0.99243692],
       [0.99243692, 1.        ]])

In [39]:
height = np.array([6,5.92,5.58,5.92])
foot = np.array([13,11,12,10])
np.corrcoef(height,foot)[0][1]

np.float64(-0.06897371912250952)

HW 1 Review